// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC185HdUKuks5YVT7QQnmpCyVvaEU7ldZM',
    appId: '1:676413589037:web:fcd3af9b54bf525d2a1aa4',
    messagingSenderId: '676413589037',
    projectId: 'fir-app-97b7c',
    authDomain: 'fir-app-97b7c.firebaseapp.com',
    storageBucket: 'fir-app-97b7c.appspot.com',
    measurementId: 'G-RWZK8S2P7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQXrAEpY7u7Hm3nVov8sZvnF1MabFzmJs',
    appId: '1:676413589037:android:7071615c427ab1b32a1aa4',
    messagingSenderId: '676413589037',
    projectId: 'fir-app-97b7c',
    storageBucket: 'fir-app-97b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwBgGt2kCdQXQD0__9AdKy8ENGHNcQRBE',
    appId: '1:676413589037:ios:adbe5ec00457fec32a1aa4',
    messagingSenderId: '676413589037',
    projectId: 'fir-app-97b7c',
    storageBucket: 'fir-app-97b7c.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwBgGt2kCdQXQD0__9AdKy8ENGHNcQRBE',
    appId: '1:676413589037:ios:e6d747750d7046312a1aa4',
    messagingSenderId: '676413589037',
    projectId: 'fir-app-97b7c',
    storageBucket: 'fir-app-97b7c.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
